routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/user' , function (){
    return "this is simple user";
})->middleware('admin' , 'admin:false');
Route::get('/admin', function () {
    return "this is admin";
});

Route::get('/posts', 'PostController@index');
Route::get('/form/edit' , 'PostController@edit');

Route::get('/form/create', 'PostController@create');
Route::get('/getuser' , 'CocaCola@getUsers');
Route::resource('/categories' , 'CategoryController');
Route::resource('/news' , 'NewsController');

resources/views/admin.blade.php
@extends('layouts.master')
@section('content')

    <h3>this is admin page</h3>

    @stop

resources/views/categoryEdit.blade.php
@extends('layouts.master')
@section('content')
    <form class="form-horizontal" action="{{route('categories.update' , ['for_up_cat' => $for_up_cat])}}" method="post">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label class="control-label col-sm-2" for="categoryName">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="categoryName" name="categoryName" required  value="{{$for_up_cat->name}}">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="submit">
            </div>
        </div>
    </form>

@stop

resources/views/categoryIndex.blade.php
@extends('layouts.master')
@section('content')

    <table class="table table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Category Name</th>
            <th >Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($categories as $category)
            <tr >
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td class="d-flex">
                    <a href="{{route('categories.edit' , ['id' => $category->id])}}" class="btn btn-primary">Edit</a>
                    <form action="{{route('categories.destroy' , ['id' => $category->id])}}" method="post">
                        @method('DELETE')
                        @csrf
                        <input type="submit" class="btn btn-danger" value="delete">
                    </form>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
    <br>
    <a href="{{route('categories.create')}}" class="btn btn-success">Create</a>
@stop

resources/views/createCategory.blade.php
@extends('layouts.master')
@section('content')
    <form class="form-horizontal" action="{{route('categories.store')}}" method="post">
        @method('POST')
        @csrf
        <div class="form-group">
            <label class="control-label col-sm-2" for="categoryName">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="categoryName" name="categoryName" required placeholder="Enter category name">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-primary" value="submit">
            </div>
        </div>
    </form>

@stop

resources/views/edit.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h3>This is edit blade</h3>

</body>
</html>

resources/views/form.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>This is form blade</h1>
</body>
</html>